// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
	aws_app_analytics: 'enable',
	aws_cognito_identity_pool_id:
		'us-east-2:ddaf772b-5256-46d8-a0bd-e48e08eb6d4d',
	aws_cognito_region: 'us-east-2',
	aws_content_delivery: 'enable',
	aws_content_delivery_bucket: 'aaltoapp-hosting-mobilehub-214087335',
	aws_content_delivery_bucket_region: 'us-east-2',
	aws_content_delivery_cloudfront: 'enable',
	aws_content_delivery_cloudfront_domain: 'd1rp5mdmq3agaf.cloudfront.net',
	aws_mobile_analytics_app_id: 'c931ae7ddb954d28b9b9a8c5a6ffd178',
	aws_mobile_analytics_app_region: 'us-east-1',
	aws_project_id: '9557388b-bfa2-4792-ac8d-73a305743d11',
	aws_project_name: 'aalto-app-2018-11-27-21-25-02',
	aws_project_region: 'us-east-2',
	aws_resource_name_prefix: 'aaltoapp-mobilehub-214087335'
}

export default awsmobile
