// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
	aws_app_analytics: 'enable',
	aws_cognito_identity_pool_id:
		'us-east-2:a0c121c3-2ad5-4c55-8c02-43ce4ec6523d',
	aws_cognito_region: 'us-east-2',
	aws_content_delivery: 'enable',
	aws_content_delivery_bucket: 'creatio-hosting-mobilehub-1502655837',
	aws_content_delivery_bucket_region: 'us-east-2',
	aws_content_delivery_cloudfront: 'enable',
	aws_content_delivery_cloudfront_domain: 'd1h6soy39ikw1m.cloudfront.net',
	aws_mobile_analytics_app_id: '50c87ac4ee384932a1265829cb676c9e',
	aws_mobile_analytics_app_region: 'us-east-1',
	aws_project_id: '6f5c664b-6f5e-4e51-8778-b8a87d0ae23e',
	aws_project_name: 'creatio',
	aws_project_region: 'us-east-2',
	aws_resource_name_prefix: 'creatio-mobilehub-1502655837',
	aws_sign_in_enabled: 'enable',
	aws_user_files: 'enable',
	aws_user_files_s3_bucket: 'creatio-userfiles-mobilehub-1502655837',
	aws_user_files_s3_bucket_region: 'us-east-2',
	aws_user_pools: 'enable',
	aws_user_pools_id: 'us-east-2_o1Op85Mw6',
	aws_user_pools_web_client_id: '1n2i941batv5hjb6avjtnmdcgt'
}

export default awsmobile
